### ISSUE TITLE
Contentrec errors upon upgrade to 0.16

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5005]
## Summary

Learner is unable to see the contentrec page upon upgrade with `Unexpected error: 'NoneType' object has no attribute '__getitem__'` error appearing.

## Branch or installer method

0.14 installation on XP, upgraded to 0.16 (build 177). 

## Screenshots

![contentrec-error](https://cloud.githubusercontent.com/assets/1457929/13833704/869ab28e-ebe8-11e5-851f-b604ce7d9dd9.png)

Progress report, for comparison, had listed 4 topics with several videos & exercises worked on, so there should be something in the contentrec.

**Comment by radinamatic** [comment]
Confirmed identical error message on 0.14.2 installation on Windows 7, after upgrade to 0.16 (build 177).

**Comment by radinamatic** [comment]
Cannot find the PR that eventually dealt with this, but I'm not seeing it on 0.16 (build 182), upgraded from 0.13 on Windows 7.

**Comment by radinamatic** [comment]
On another hand, contentrec does not seem to be working of-the-bat after the upgrade. This user had started several exercises and videos, has over 700 points and can see his progress report correctly, but nothing is displayed in the contentrec page on the first login after the upgrade. 

![contentrec-error-0 13-to-0 16](https://cloud.githubusercontent.com/assets/1457929/13901829/2fd19396-ee31-11e5-8771-6a5ef3708d13.png)

Only after doing something in this 0.16 version, user can see some recommendation.

**Comment by radinamatic** [comment]
Confirmed error form the original issue on Ubuntu 14.04 (KA Lite version 0.14.2 upgraded to 0.16b2 via PPA). 

However, upon contentrec page reload the error is not present anymore, and recommendations are there... :smiley_cat:

**Comment by radinamatic** [comment]
Reviewing this on OSX with latest 95 build:

If the content/language pack set as default for a Learner user has not been installed/updated (Danish on below screenshot), they will see the `Unexpected error: no such table: item` when landing on contentrec page:

![contentrec-no-langpack](https://cloud.githubusercontent.com/assets/1457929/13961440/fc6ccc68-f05c-11e5-9f08-76911197190b.png)

This may be address with what I suggested in #5003:
  -  Documenting the need to install new contentpacks (easy & lazy :wink: )
  -  Insert alert message on `Manage > Videos` page if no new contentpack is detected (bit more work, but better user experience)

--------------------------------------------
Even if the new content/language pack is there, no errors appear but it may take a couple of seconds for contentrec page to load. Could we possibly insert the `Connecting to server, please wait...` alert from #4936 here too?

**Comment by radinamatic** [comment]
Seeing again the original `Unexpected error: 'NoneType' object has no attribute '__getitem__'` while upgrading OSX from 0.15 to 0.16 with build 95. Portuguese language pack updated correctly from the Admin `Manage > Languages` tab, but when I switch to Learner who has Portuguese language set as default, error is still there:

![contentrec-no-langpack2](https://cloud.githubusercontent.com/assets/1457929/14023663/b3e53680-f1e5-11e5-8bab-d7984f1712ed.png)

@aronasorman @rtibbles

**Comment by aronasorman** [comment]
@radinamatic when you installed the new pt lang pack, did you restart your server as well?

**Comment by radinamatic** [comment]
I thought that was not the requirement anymore in this version... :pensive:

**Comment by aronasorman** [comment]
I'm not sure too, but can you see if restarting it will make it work? It might be an edge case with going from a pre-0.16 lang pack to the new one.

**Comment by radinamatic** [comment]
Edge case indeed... :stuck_out_tongue: 
Added to documentation TODO!

**Comment by aronasorman** [comment]
Taking over this. The agreed upon solution is to show an alert when admins log in, regarding the need to refresh their language packs.

**Comment by rtibbles** [comment]
Fixed in #5040
